# Generated by Django 6.0.2 on 2026-03-05 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project_is_featured_alter_project_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='is_featured',
        ),
    ]
